[package]
name = "mssql-python-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "mssql_python_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
pyo3-asyncio = { version = "0.20", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["full"] }
tiberius = "0.12"
tokio-util = { version = "0.7", features = ["compat"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"